### ISSUE TITLE
ER_NO_SUCH_TABLE: Table 'sshub.traffic' doesn't exist

### ISSUE THREAD

**Issue by thekingofcity** [shadowsocks/shadowsocks-hub#4]
I have no idea why this prompt up.
What's checked:
  * newest version
  * `knex migrate:latest --env production`
  * mysql account has access to `traffic`

What's may mess the things up is that I have imported old backup data into new database, but I have no idea how to check it out.

```
root@server:~/shadowsocks-hub# pm2 logs sshub --lines 50
[TAILING] Tailing last 50 lines for [sshub] process (change the value with --lines option)
/root/.pm2/logs/sshub-out.log last 50 lines:
0|sshub    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:

/root/.pm2/logs/sshub-error.log last 50 lines:
0|sshub    |     --------------------
0|sshub    |     at Protocol._enqueue (/root/shadowsocks-hub/node_modules/mysql/lib/protocol/Protocol.js:144:48)
0|sshub    |     at Connection.query (/root/shadowsocks-hub/node_modules/mysql/lib/Connection.js:200:25)
0|sshub    |     at /root/shadowsocks-hub/node_modules/knex/lib/dialects/mysql/index.js:161:18
0|sshub    |     at Promise._execute (/root/shadowsocks-hub/node_modules/bluebird/js/release/debuggability.js:313:9)
0|sshub    |     at Promise._resolveFromExecutor (/root/shadowsocks-hub/node_modules/bluebird/js/release/promise.js:483:18)
0|sshub    |     at new Promise (/root/shadowsocks-hub/node_modules/bluebird/js/release/promise.js:79:10)
0|sshub    |     at Client_MySQL._query (/root/shadowsocks-hub/node_modules/knex/lib/dialects/mysql/index.js:155:12)
0|sshub    |     at Client_MySQL.query (/root/shadowsocks-hub/node_modules/knex/lib/client.js:206:17)
0|sshub    |     at Runner.<anonymous> (/root/shadowsocks-hub/node_modules/knex/lib/runner.js:155:36)
0|sshub    |     at Runner.tryCatcher (/root/shadowsocks-hub/node_modules/bluebird/js/release/util.js:16:23)
0|sshub    |     at Runner.query (/root/shadowsocks-hub/node_modules/bluebird/js/release/method.js:15:34)
0|sshub    |     at /root/shadowsocks-hub/node_modules/knex/lib/runner.js:61:21
0|sshub    |     at tryCatcher (/root/shadowsocks-hub/node_modules/bluebird/js/release/util.js:16:23)
0|sshub    |     at /root/shadowsocks-hub/node_modules/bluebird/js/release/using.js:185:26
0|sshub    |     at tryCatcher (/root/shadowsocks-hub/node_modules/bluebird/js/release/util.js:16:23)
0|sshub    |     at Promise._settlePromiseFromHandler (/root/shadowsocks-hub/node_modules/bluebird/js/release/promise.js:512:31)
0|sshub    | (node:14719) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
0|sshub    | (node:14719) UnhandledPromiseRejectionWarning: Error: ER_NO_SUCH_TABLE: Table 'sshub.traffic' doesn't exist
0|sshub    |     at Query.Sequence._packetToError (/root/shadowsocks-hub/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
0|sshub    |     at Query.ErrorPacket (/root/shadowsocks-hub/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
0|sshub    |     at Protocol._parsePacket (/root/shadowsocks-hub/node_modules/mysql/lib/protocol/Protocol.js:278:23)
0|sshub    |     at Parser.write (/root/shadowsocks-hub/node_modules/mysql/lib/protocol/Parser.js:76:12)
0|sshub    |     at Protocol.write (/root/shadowsocks-hub/node_modules/mysql/lib/protocol/Protocol.js:38:16)
0|sshub    |     at Socket.<anonymous> (/root/shadowsocks-hub/node_modules/mysql/lib/Connection.js:91:28)
0|sshub    |     at Socket.<anonymous> (/root/shadowsocks-hub/node_modules/mysql/lib/Connection.js:502:10)
0|sshub    |     at emitOne (events.js:116:13)
0|sshub    |     at Socket.emit (events.js:211:7)
0|sshub    |     at addChunk (_stream_readable.js:263:12)
0|sshub    |     at readableAddChunk (_stream_readable.js:250:11)
0|sshub    |     at Socket.Readable.push (_stream_readable.js:208:10)
0|sshub    |     at TCP.onread (net.js:607:20)
0|sshub    |     --------------------
0|sshub    |     at Protocol._enqueue (/root/shadowsocks-hub/node_modules/mysql/lib/protocol/Protocol.js:144:48)
0|sshub    |     at Connection.query (/root/shadowsocks-hub/node_modules/mysql/lib/Connection.js:200:25)
0|sshub    |     at /root/shadowsocks-hub/node_modules/knex/lib/dialects/mysql/index.js:161:18
0|sshub    |     at Promise._execute (/root/shadowsocks-hub/node_modules/bluebird/js/release/debuggability.js:313:9)
0|sshub    |     at Promise._resolveFromExecutor (/root/shadowsocks-hub/node_modules/bluebird/js/release/promise.js:483:18)
0|sshub    |     at new Promise (/root/shadowsocks-hub/node_modules/bluebird/js/release/promise.js:79:10)
0|sshub    |     at Client_MySQL._query (/root/shadowsocks-hub/node_modules/knex/lib/dialects/mysql/index.js:155:12)
0|sshub    |     at Client_MySQL.query (/root/shadowsocks-hub/node_modules/knex/lib/client.js:206:17)
0|sshub    |     at Runner.<anonymous> (/root/shadowsocks-hub/node_modules/knex/lib/runner.js:155:36)
0|sshub    |     at Runner.tryCatcher (/root/shadowsocks-hub/node_modules/bluebird/js/release/util.js:16:23)
0|sshub    |     at Runner.query (/root/shadowsocks-hub/node_modules/bluebird/js/release/method.js:15:34)
0|sshub    |     at /root/shadowsocks-hub/node_modules/knex/lib/runner.js:61:21
0|sshub    |     at tryCatcher (/root/shadowsocks-hub/node_modules/bluebird/js/release/util.js:16:23)
0|sshub    |     at /root/shadowsocks-hub/node_modules/bluebird/js/release/using.js:185:26
0|sshub    |     at tryCatcher (/root/shadowsocks-hub/node_modules/bluebird/js/release/util.js:16:23)
0|sshub    |     at Promise._settlePromiseFromHandler (/root/shadowsocks-hub/node_modules/bluebird/js/release/promise.js:512:31)
0|sshub    | (node:14719) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
```

```
mysql> show tables
    -> ;
+----------------------+
| Tables_in_sshub      |
+----------------------+
| account              |
| admin_approval       |
| email_user           |
| knex_migrations      |
| knex_migrations_lock |
| node                 |
| payment              |
| product              |
| purchase             |
| server               |
| ss_account           |
| traffic              |
| user                 |
+----------------------+
13 rows in set (0.00 sec)

mysql> select * from traffic;
+--------------------------------------+--------------------------------------+------------+------------------+---------------+
| id                                   | accountId                            | usage      | lastMeterReading | createdTime   |
+--------------------------------------+--------------------------------------+------------+------------------+---------------+
| 17cd5842-90ce-4943-821f-8cbb9174476d | 41086b18-1805-42d4-92ca-2c642cbb3a53 |    1204738 |          1204738 | 1537356180296 |
| 21dea69e-f4d3-4de2-855e-8b88110cbf12 | e477a97d-d7ec-4a4f-b8a6-f3c1c009d02c |  120256093 |        120256093 | 1537356180346 |
| 337d9d54-ef98-4c07-825d-aae2200518a4 | 80547596-1d49-4370-b3c1-8f4977a59cdb | 2914755990 |       2914755990 | 1537356180331 |
| 570d0afc-9e56-4e6c-a931-6e5843f99aaa | 1fc2b81a-61cb-482d-8437-82c03820d92a |  867385974 |        867385974 | 1537356180276 |
| 5714773e-4acc-4931-a1aa-d2ad57658edf | 80547596-1d49-4370-b3c1-8f4977a59cdb | 2914753899 |       2914753899 | 1537356168344 |
| 5c486c6d-69b7-4979-aed0-2652b19c6f35 | 6fef3077-57db-4f38-90cd-a814775f4920 |          0 |                0 | 1537356180322 |
| 85b8997b-42c9-49d2-b2ee-e13b7a688f8c | 5e3d7cef-6290-486d-85e9-540ef4fbefeb |          0 |                0 | 1537356180313 |
| c0fa33fd-030b-4c53-bf71-e3967b879408 | a8d87d32-8008-4f49-a47e-52b101113dda | 5879920021 |       5879920021 | 1537356180339 |
| e809e965-0ece-4de7-89f6-e324b60a400a | 1fc2b81a-61cb-482d-8437-82c03820d92a |  867384710 |        867384710 | 1537356168274 |
+--------------------------------------+--------------------------------------+------------+------------------+---------------+
9 rows in set (0.00 sec)
```

**Comment by Eggham** [comment]
Interesting! Apparently `sshub.traffic` table DID exist from what you posted. It would be very helpful if you could do a bit of debugging in order to narrowing the problem. What I can think of are the follows:
1. Can this bug be reproduced?
2. If so, can you log in as the admin (testing if reading user table works fine)?
3. If so, can you successfully create a new user, a new product, a new server, a new node, a new request, a new approval, a new account (testing writing to other tables works fine)?
 4. If so, can you backup the existing `sshub` database and then rollback all the tables by running `knex migrate:rollback --env production` (you may run this command several times until nothing in the database execpt for `knex_migrations` and `knex_migrations_lock` tables). After that, run `knex migrate:latest --env production` to create all the tables again. Then please check if the problem persist.
5. If so, can you please re-install the code from the scratch (perhaps by re-cloning the code from github and install it from in a different directory) and check if the problem persist.

I guess by doing it we may narrow down the problem. And we will see how to solve the problem/improve the system.

**Comment by thekingofcity** [comment]
The first three questions are true, and since the fourth one need more time, I will comment as soon as possible when I run these commands. :)
